### ISSUE TITLE
PHP migrate fire errors on step 5

### ISSUE THREAD

**Issue by faridsa** [zhiephie/boilerplate-slim3#10]
I've followed your instructions to set up your boilerplate, but I got these errors when running migrate.
```
Fatal error: Uncaught exception 'Illuminate\Contracts\Container\BindingResolutionException' with message 'Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable.' in /Volumes/data/Sites/scotch-box/public/slim/vendor/illuminate/container/Container.php:763
Stack trace:
#0 /Volumes/data/Sites/scotch-box/public/slim/vendor/illuminate/container/Container.php(644): Illuminate\Container\Container->build('Illuminate\\Cont...', Array)
#1 /Volumes/data/Sites/scotch-box/public/slim/vendor/illuminate/database/Connectors/ConnectionFactory.php(130): Illuminate\Container\Container->make('Illuminate\\Cont...')
#2 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#3 /Volumes/data/Sites/scotch-box/public/slim/vendor/illuminate/database/Connection.php(964): call_user_func(Object(Closure))
#4 /Volumes/data/Sites/scotch-box/public/slim/vendor/illuminate/database/Connection.php(832): Illuminate\Database\Connection->getPdo()
#5 /Volumes/data/Sites/scotch-box/publi in /Volumes/data/Sites/scotch-box/public/slim/vendor/illuminate/container/Container.php on line 763
```

**Comment by zhiephie** [comment]
if you have a database configuration? and support PDO ext?

**Comment by faridsa** [comment]
Thank you for your reply.

I'm testing your boilerplate in a **vagrant scotch box 2.5** environment, alongside another two slim3 projects under development, which are based on akrabat boilerplate. 
None of these fires similar errors.
Regards.

**Comment by zhiephie** [comment]
Okay I'll try later and trace your error.
