### ISSUE TITLE
Running php migrate returns errors

### ISSUE THREAD

**Issue by visualcookie** [zhiephie/boilerplate-slim3#4]
```
C:\Ampps\www\boilerplate-slim3 (master)
λ php migrate
PHP Fatal error:  Uncaught PDOException: could not find driver in C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\Connector.php:55
Stack trace:
#0 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', 'mysql', Array)
#1 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connection.php(864): call_user_func(Object(Closure))
#5 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connection.php(732): Illuminate\Database\Connection->getPdo()
#6 C:\Ampps\www\b in C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\Connector.php on line 55

Fatal error: Uncaught PDOException: could not find driver in C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\Connector.php:55
Stack trace:
#0 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', 'mysql', Array)
#1 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connection.php(864): call_user_func(Object(Closure))
#5 C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connection.php(732): Illuminate\Database\Connection->getPdo()
#6 C:\Ampps\www\b in C:\Ampps\www\boilerplate-slim3\vendor\illuminate\database\Connectors\Connector.php on line 55
```

**Comment by zhiephie** [comment]
You need to have a module called pdo_mysql. Looking for following in phpinfo()

```
pdo_mysql

PDO Driver for MySQL
```

**Comment by zhiephie** [comment]
Following requirements 

https://github.com/zhiephie/boilerplate-slim3/commit/33246011131656ecef0ac474d3cedfab00f2ceb2

**Comment by visualcookie** [comment]
Awesome, thanks. Seems like I haven't activated it. :+1:

**Comment by zhiephie** [comment]
:+1:
